### ISSUE TITLE
Update nameservers for separate DNS service

### ISSUE THREAD

**Issue by abagshaw** [tiramiseb/terraform-provider-gandi#5]
Is it possible to just set the nameservers in the terraform config to facilitate using a different DNS service (not Gandi's LiveDNS)?

**Comment by tiramiseb** [comment]
Do you mean there are other services with the same API ?

**Comment by abagshaw** [comment]
I'm not sure - I'm not familiar with the Gandi API at all. All I'm wanting to do is use Google Cloud's DNS and then plug in the Google Cloud DNS nameservers into my domain's config all using terraform.

**Comment by tiramiseb** [comment]
Oh I see. I did not understand your request :)

If I understood correctly, you want to set the nameservers like you would manually on https://admin.gandi.net/domain/<uuid>/<domain_name>/nameservers, to point to the Google DNS service, and then use the Google Cloud Terraform provider to configure your DNS records.


You want to use https://www.terraform.io/docs/providers/google/r/dns_managed_zone.html#name_servers to fetch Google's nameservers and inject them in the Gandi configuration, using the API.

AFAIK, the LiveDNS API doesn't have any endpoint to do so.

I suggest you contact Gandi to ask them for a way to do that programmatically. If they provide an endpoint for this in the LiveDNS API, I would be able to implement it.


I will close this issue for now because I don't know any way to do it with this API, but feel free to re-open it if you have any further information that would allow implementing it.

**Comment by abagshaw** [comment]
@tiramiseb Yup that's exactly what I'm trying to do, ok I might open a feature request with Gandi. Thanks!

**Comment by abagshaw** [comment]
@tiramiseb Yup, that's exactly what I'm trying to do. What about [this api](http://doc.rpc.gandi.net/domain/usage.html#domain-nameservers-set-usage)? Would that provide the functionality necessary to implement nameserver configuration in terraform?

**Comment by abagshaw** [comment]
Ok I see, thanks!

**Comment by tiramiseb** [comment]
Thanks @baloo for the details.

I personally will not be leader on this type of requests, simply because this provider is meant for the simple use-case where DNS records are managed on Gandi servers. I would be happy to implement new LiveDNS features in this provider, or to merge some PRs.

If you implement @abagshaw 's request (being able to change the nameservers for a domain) with LiveDNS, I can implement it in the provider :wink: 

However, I will not include the other API in this provider, for a very simple reason : I'm a big fan of dogfooding and I maintain only stuff that I use, and I only use the LiveDNS API... I'd be happy to share ownership on this project if someone else wants to maintain the other API's part.

BTW, yes I personally have a request... It would be great to have all features in the LiveDNS API documentation - currently, there are undocumented features (see https://github.com/tiramiseb/terraform-provider-gandi/issues/3#issuecomment-394861337 for instance)...

**Comment by baloo** [comment]
> If you implement @abagshaw 's request (being able to change the nameservers for a domain) with LiveDNS, I can implement it in the provider 

It's a different subsystem (one that talks to registry with EPP). So it's uneasy to add this in livedns itself. Another restful API is coming.

> BTW, yes I personally have a request... It would be great to have all features in the LiveDNS API documentation - currently, there are undocumented features (see #3 (comment) for instance)...

Yeah, our documentation sucks :( We're working on that. I'll try to look around and add what's missing.
